# File generated by CompCert 3.9
# Command line: -Obranchless -c -dasm c.c
	.text
	.align	16
iter:
	.cfi_startproc
	subq	$56, %rsp
	.cfi_adjust_cfa_offset	56
	leaq	64(%rsp), %rax
	movq	%rax, 0(%rsp)
	movq	%rbx, 8(%rsp)
	movq	%rbp, 16(%rsp)
	movq	%r12, 24(%rsp)
	movq	%r13, 32(%rsp)
	movq	%r14, 40(%rsp)
	movq	%rcx, %rbx
	movq	%rdx, %rbp
	movq	%rsi, %r12
	movq	%rdi, %r13
	xorq	%r14, %r14
.L100:
	cmpq	%r12, %r14
	jae	.L101
	movl	0(%r13,%r14,4), %esi
	movq	%rbx, %rdi
	call	*%rbp
	leaq	1(%r14), %r14
	jmp	.L100
.L101:
	movq	8(%rsp), %rbx
	movq	16(%rsp), %rbp
	movq	24(%rsp), %r12
	movq	32(%rsp), %r13
	movq	40(%rsp), %r14
	addq	$56, %rsp
	ret
	.cfi_endproc
	.type	iter, @function
	.size	iter, . - iter
	.text
	.align	16
accum:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	0(%rdi), %ecx
	leal	0(%ecx,%esi,1), %edx
	movl	%edx, 0(%rdi)
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	accum, @function
	.size	accum, . - accum
	.text
	.align	16
	.globl iter_accum
iter_accum:
	.cfi_startproc
	subq	$40, %rsp
	.cfi_adjust_cfa_offset	40
	leaq	48(%rsp), %rax
	movq	%rax, 0(%rsp)
	leaq	iter(%rip), %r8
	movq	%r8, 8(%rsp)
	leaq	accum(%rip), %r8
	movq	%r8, 16(%rsp)
	xorl	%edx, %edx
	movl	%edx, 24(%rsp)
	leaq	accum(%rip), %rdx
	leaq	24(%rsp), %rcx
	call	iter
	movl	24(%rsp), %eax
	addq	$40, %rsp
	ret
	.cfi_endproc
	.type	iter_accum, @function
	.size	iter_accum, . - iter_accum
